### ISSUE TITLE
unable to get Kubernetes cluster up

### ISSUE THREAD

**Issue by ompraash** [apprenda/kismatic-provision#25]
I have been trying to get kismatic install for the kube cluster but keeps failing as below

Installing Cluster===========================================================
Configure Cluster Prerequisites                                                 [OK]
Update Hosts File                                                               [OK]
Deploy Cluster Certificates                                                     [OK]
Generate Kubectl Config File                                                    [OK]
Deploy Etcd Certificates                                                        [OK]
Configure Kismatic Package Repos                                                [OK]
Start Kubernetes Etcd Cluster                                                   [OK]
Start Network Etcd Cluster                                                      [OK]
Start Docker                                                                    [OK]
Start Kubernetes Kubelet                                                        [OK]
Start Kubernetes API Server                                                     [OK]
Start Kubernetes Scheduler                                                      [OK]
Start Kubernetes Controller Manager                                             [OK]
Validate Kubernetes Control Plane is Running                                    [ERROR]
- Task: wait until kube-apiserver-master01 pod has the desired version
  master01:                                                                     [ERROR]
---- STDERR ----
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
---------------
error installing: error running playbook: error running ansible: exit status 2

The environment is vagrant - centos.

**Comment by dkoshkin** [comment]
Did you use the `cluster.networking.update_hosts_files: true` flag. This is most likely required unless you have DNS in your vagrant cluster.
Also what is your `master.load_balanced_fqdn` set to?

**Comment by ompraash** [comment]
master:                                  # Here you will identify all of the nodes that should play the master role.
  expected_count: 1
  load_balanced_fqdn: "192.168.204.14"                 
  load_balanced_short_name: "master01"          
  nodes:
  - host: "master01"
    ip: "192.168.204.14"
    internalip: ""
worker:                                  
  expected_count: 1
  nodes:
  - host: "worker01"
    ip: "192.168.204.15"
    internalip: ""

**Comment by dkoshkin** [comment]
And what does `cluster.networking.update_hosts_files:` look like?

**Comment by ompraash** [comment]
it is set to "true".

**Comment by dkoshkin** [comment]
Ok that seems all correct, can you run `kismatic diagnose` command and share the api server logs on the master?

**Comment by ompraash** [comment]
Diagnose was all good.

```
./kismatic diagnose
Reading plan file                                                               [OK]
Validate SSH connectivity to nodes                                              [OK]
Diagnose Nodes                                                                  [OK]
```

On executing "kismatic install apply" The error is:

```
Validate Kubernetes Control Plane is Running
- [master01] Retrying: wait until kube-apiserver-master01 pod has the desired version (20/20 attempts)
```

**Comment by dkoshkin** [comment]
Ahh sorry I should have specified, you would need to go into the `diagnostics` folder where you run the command from and manually look at the logs

**Comment by ompraash** [comment]
[diagnostics-etcd01.tar.gz](https://github.com/apprenda/kismatic-provision/files/962704/diagnostics-etcd01.tar.gz)
[diagnostics-master01.tar.gz](https://github.com/apprenda/kismatic-provision/files/962705/diagnostics-master01.tar.gz)
[diagnostics-worker01.tar.gz](https://github.com/apprenda/kismatic-provision/files/962703/diagnostics-worker01.tar.gz)

**Comment by ompraash** [comment]
i have added the new diagnose files.

[diagnostics-etcd01.tar.gz](https://github.com/apprenda/kismatic-provision/files/962708/diagnostics-etcd01.tar.gz)
[diagnostics-master01.tar.gz](https://github.com/apprenda/kismatic-provision/files/962709/diagnostics-master01.tar.gz)
[diagnostics-worker01.tar.gz](https://github.com/apprenda/kismatic-provision/files/962710/diagnostics-worker01.tar.gz)

**Comment by dkoshkin** [comment]
Can you also upload the `runs/` directory?

**Comment by ompraash** [comment]
[runs.zip](https://github.com/apprenda/kismatic-provision/files/962732/runs.zip)

**Comment by dkoshkin** [comment]
Did you generate you own certs or let Kismatic do it for you?

**Comment by ompraash** [comment]
Defaults. Only for docker we are trying to connect local repo.

**Comment by dkoshkin** [comment]
Ok I was going to suggest that, also what version of KET are you using? There is an updated version we released yesterday. https://github.com/apprenda/kismatic/releases/tag/v1.3.1

**Comment by ompraash** [comment]
in the validate pod yml

`    # kubeconfig is required becuase this task can be triggered from any k8s node
  - name: wait until {{ item }} pod has the desired version
    command: kubectl get pods {{ item }} --namespace kube-system -o jsonpath='{.metadata.annotations.kismatic/version}' --kubeconfig {{ kubernetes_kubeconfig_path }}
    register: podVersion
    until: podVersion.stdout == kismatic_short_version
    retries: 40
    delay: 10`

Giving a try with this option.

**Comment by alexbrand** [comment]
@ompraash I recommend bumping up the memory in your vagrantfile to 2Gb.

**Comment by dkoshkin** [comment]
You would need to change it in the kube-api [spec](https://github.com/apprenda/kismatic/blob/master/ansible/roles/kube-apiserver/templates/kube-apiserver.yaml#L63), but I would recommend upgrading to the new KET release you can keep your plan file just place it in the new folder.

**Comment by ompraash** [comment]
I see the error as below

`[vagrant@master01 ~]$ sudo docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED                  STATUS                  PORTS               NAMES
90937c420946        6a29f77d1186                               "kube-apiserver --adm"   Less than a second ago   Up Less than a second                       k8s_kube-apiserver_kube-apiserver-master01_kube-system_e893f59008b0e8d4c295c9727dbc8717_4
53a23b9e4df9        dc78cc207023                               "kube-controller-mana"   2 minutes ago            Up 2 minutes                                k8s_kube-controller-manager_kube-controller-manager-master01_kube-system_88ccfeb4d1e074cfb9201c01c4623bb1_0
9279efcb9323        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 2 minutes ago            Up 2 minutes                                k8s_POD_kube-controller-manager-master01_kube-system_88ccfeb4d1e074cfb9201c01c4623bb1_0
f996ab8952c0        dc03ae0150c9                               "kube-scheduler --kub"   2 minutes ago            Up 2 minutes                                k8s_kube-scheduler_kube-scheduler-master01_kube-system_c81883702f999a37656e431ba0984a41_0
4515795bf3fd        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 2 minutes ago            Up 2 minutes                                k8s_POD_kube-scheduler-master01_kube-system_c81883702f999a37656e431ba0984a41_0
d0820ab4cb86        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 2 minutes ago            Up 2 minutes                                k8s_POD_kube-apiserver-master01_kube-system_e893f59008b0e8d4c295c9727dbc8717_0
[vagrant@master01 ~]$ sudo docker log 90937c420946
docker: 'log' is not a docker command.
See 'docker --help'.
[vagrant@master01 ~]$ sudo docker logs 90937c420946
I0427 20:35:19.005816       1 server.go:224] Initializing deserialization cache size based on 0MB limit
I0427 20:35:19.008128       1 server.go:420] Initializing cache sizes based on 0MB limit
I0427 20:35:19.043146       1 master.go:323] Enabling API group "authentication.k8s.io".
I0427 20:35:19.043179       1 master.go:323] Enabling API group "authorization.k8s.io".
I0427 20:35:19.044397       1 master.go:323] Enabling API group "autoscaling".
I0427 20:35:19.053650       1 master.go:323] Enabling API group "batch".
I0427 20:35:19.055040       1 master.go:323] Enabling API group "certificates.k8s.io".
I0427 20:35:19.062949       1 master.go:323] Enabling API group "extensions".
I0427 20:35:19.063626       1 master.go:323] Enabling API group "policy".
I0427 20:35:19.081650       1 master.go:323] Enabling API group "rbac.authorization.k8s.io".
I0427 20:35:19.082417       1 master.go:323] Enabling API group "settings.k8s.io".
I0427 20:35:19.084022       1 master.go:323] Enabling API group "storage.k8s.io".
I0427 20:35:19.096775       1 master.go:323] Enabling API group "apps".
[restful] 2017/04/27 20:35:19 log.go:30: [restful/swagger] listing is available at https://192.168.205.11:6443/swaggerapi/
[restful] 2017/04/27 20:35:19 log.go:30: [restful/swagger] https://192.168.205.11:6443/swaggerui/ is mapped to folder /swagger-ui/
I0427 20:35:19.308010       1 serve.go:79] Serving securely on 0.0.0.0:6443
I0427 20:35:19.308099       1 serve.go:94] Serving insecurely on 127.0.0.1:8080
I0427 20:35:19.759317       1 wrap.go:75] GET /api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: (630.703µs) 200 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:19.759705       1 wrap.go:75] GET /api/v1/pods?fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: (189.227µs) 200 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:19.759953       1 wrap.go:75] GET /apis/apps/v1beta1/statefulsets?resourceVersion=0: (159.563µs) 200 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:19.760285       1 wrap.go:75] GET /api/v1/nodes?resourceVersion=0: (252.112µs) 200 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:19.760528       1 wrap.go:75] GET /api/v1/persistentvolumeclaims?resourceVersion=0: (162.998µs) 200 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:19.760782       1 wrap.go:75] GET /api/v1/persistentvolumes?resourceVersion=0: (169.754µs) 200 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:19.768237       1 wrap.go:75] GET /api/v1/replicationcontrollers?resourceVersion=0: (367.95µs) 200 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:19.768647       1 wrap.go:75] GET /apis/extensions/v1beta1/replicasets?resourceVersion=0: (218.88µs) 200 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:19.768872       1 rest.go:320] Starting watch for /api/v1/nodes, rv=23 labels= fields= timeout=5m56s
I0427 20:35:19.769479       1 rest.go:320] Starting watch for /api/v1/persistentvolumeclaims, rv=23 labels= fields= timeout=6m11s
I0427 20:35:19.769682       1 rest.go:320] Starting watch for /api/v1/persistentvolumes, rv=23 labels= fields= timeout=8m8s
I0427 20:35:19.769939       1 rest.go:320] Starting watch for /api/v1/pods, rv=23 labels= fields=spec.nodeName!=,status.phase!=Failed,status.phase!=Succeeded timeout=5m38s
I0427 20:35:19.770155       1 rest.go:320] Starting watch for /api/v1/pods, rv=23 labels= fields=spec.nodeName=,status.phase!=Failed,status.phase!=Succeeded timeout=6m24s
I0427 20:35:19.770329       1 rest.go:320] Starting watch for /apis/apps/v1beta1/statefulsets, rv=23 labels= fields= timeout=7m3s
I0427 20:35:19.772586       1 wrap.go:75] GET /api/v1/services?resourceVersion=0: (287.89µs) 200 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:19.772787       1 rest.go:320] Starting watch for /apis/extensions/v1beta1/replicasets, rv=23 labels= fields= timeout=7m10s
I0427 20:35:19.773040       1 rest.go:320] Starting watch for /api/v1/replicationcontrollers, rv=23 labels= fields= timeout=8m7s
I0427 20:35:19.774518       1 rest.go:320] Starting watch for /api/v1/services, rv=23 labels= fields= timeout=7m45s
I0427 20:35:19.775146       1 wrap.go:75] GET /api/v1/services?resourceVersion=0: (220.997µs) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:19.775489       1 wrap.go:75] GET /api/v1/nodes?fieldSelector=metadata.name%3Dworker01&resourceVersion=0: (298.716µs) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:19.775491       1 wrap.go:75] GET /api/v1/pods?fieldSelector=spec.nodeName%3Dworker01&resourceVersion=0: (236.056µs) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:19.777388       1 rest.go:320] Starting watch for /api/v1/services, rv=23 labels= fields= timeout=9m15s
I0427 20:35:19.777594       1 wrap.go:75] GET /api/v1/pods?fieldSelector=spec.nodeName%3Dmaster01&resourceVersion=0: (264.131µs) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36604]
I0427 20:35:19.777692       1 rest.go:320] Starting watch for /api/v1/nodes, rv=23 labels= fields=metadata.name=worker01 timeout=6m38s
I0427 20:35:19.777889       1 wrap.go:75] GET /api/v1/services?resourceVersion=0: (196.205µs) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36604]
I0427 20:35:19.778038       1 rest.go:320] Starting watch for /api/v1/pods, rv=23 labels= fields=spec.nodeName=worker01 timeout=8m12s
I0427 20:35:19.778159       1 wrap.go:75] GET /api/v1/nodes?fieldSelector=metadata.name%3Dmaster01&resourceVersion=0: (183.885µs) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36604]
I0427 20:35:19.779173       1 rest.go:320] Starting watch for /api/v1/nodes, rv=23 labels= fields=metadata.name=master01 timeout=5m50s
I0427 20:35:19.779442       1 rest.go:320] Starting watch for /api/v1/pods, rv=23 labels= fields=spec.nodeName=master01 timeout=7m22s
I0427 20:35:19.779472       1 rest.go:320] Starting watch for /api/v1/services, rv=23 labels= fields= timeout=7m21s
I0427 20:35:20.856125       1 wrap.go:75] GET /api/v1/namespaces/kube-system/endpoints/kube-scheduler: (2.0418ms) 404 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:21.437215       1 wrap.go:75] GET /api/v1/namespaces/kube-system/endpoints/kube-controller-manager: (1.150807ms) 404 [[kube-controller-manager/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41936]
I0427 20:35:21.888650       1 wrap.go:75] GET /api/v1/nodes/worker01?resourceVersion=0: (437.878µs) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:21.894814       1 wrap.go:75] PATCH /api/v1/nodes/worker01/status: (3.135907ms) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:23.377124       1 wrap.go:75] PATCH /api/v1/namespaces/default/events/worker01.14b95b4f8126a0a9: (1.569138ms) 404 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:23.974444       1 wrap.go:75] PATCH /api/v1/namespaces/default/events/master01.14b95b4f8e2c42f9: (1.285083ms) 404 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36604]
I0427 20:35:26.941213       1 wrap.go:75] GET /api/v1/namespaces/kube-system/pods/kube-apiserver-master01: (1.268267ms) 404 [[kubectl/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36614]
I0427 20:35:26.942836       1 wrap.go:75] GET /api/v1/namespaces/kube-system: (962.236µs) 404 [[kubectl/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36614]
I0427 20:35:28.632109       1 wrap.go:75] GET /api/v1/nodes/master01?resourceVersion=0: (407.937µs) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36604]
I0427 20:35:28.637982       1 wrap.go:75] PATCH /api/v1/nodes/master01/status: (3.012523ms) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36604]
I0427 20:35:30.857909       1 trace.go:61] Trace "Create /api/v1/namespaces/kube-system/endpoints" (started 2017-04-27 20:35:20.857087934 +0000 UTC):
[30.745µs] [30.745µs] About to convert to expected version
[165.612µs] [134.867µs] Conversion done
"Create /api/v1/namespaces/kube-system/endpoints" [10.000783193s] [10.000617581s] END
I0427 20:35:30.857987       1 wrap.go:75] POST /api/v1/namespaces/kube-system/endpoints: (10.001043206s) 403 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
I0427 20:35:31.438291       1 trace.go:61] Trace "Create /api/v1/namespaces/kube-system/endpoints" (started 2017-04-27 20:35:21.437931016 +0000 UTC):
[37.344µs] [37.344µs] About to convert to expected version
[90.308µs] [52.964µs] Conversion done
"Create /api/v1/namespaces/kube-system/endpoints" [10.000330138s] [10.00023983s] END
I0427 20:35:31.438346       1 wrap.go:75] POST /api/v1/namespaces/kube-system/endpoints: (10.000526078s) 403 [[kube-controller-manager/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41936]
I0427 20:35:31.896895       1 wrap.go:75] GET /api/v1/nodes/worker01?resourceVersion=0: (407.677µs) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:31.902805       1 wrap.go:75] PATCH /api/v1/nodes/worker01/status: (2.755343ms) 200 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:33.378631       1 trace.go:61] Trace "Create /api/v1/namespaces/default/events" (started 2017-04-27 20:35:23.378070594 +0000 UTC):
[19.747µs] [19.747µs] About to convert to expected version
[87.892µs] [68.145µs] Conversion done
"Create /api/v1/namespaces/default/events" [10.000532819s] [10.000444927s] END
I0427 20:35:33.378731       1 wrap.go:75] POST /api/v1/namespaces/default/events: (10.000800444s) 403 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:33.381491       1 wrap.go:75] PATCH /api/v1/namespaces/default/events/worker01.14b95b4f81256b73: (1.483084ms) 404 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 192.168.205.12:56788]
I0427 20:35:33.977807       1 trace.go:61] Trace "Create /api/v1/namespaces/default/events" (started 2017-04-27 20:35:23.975201862 +0000 UTC):
[16.056µs] [16.056µs] About to convert to expected version
[62.849µs] [46.793µs] Conversion done
"Create /api/v1/namespaces/default/events" [10.002575007s] [10.002512158s] END
I0427 20:35:33.977854       1 wrap.go:75] POST /api/v1/namespaces/default/events: (10.002733939s) 403 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36604]
I0427 20:35:33.980366       1 wrap.go:75] PATCH /api/v1/namespaces/default/events/master01.14b95b4f8e2ca89b: (1.44324ms) 404 [[kubelet/v1.6.0 (linux/amd64) kubernetes/fff5156] 127.0.0.1:36604]
I0427 20:35:34.356620       1 wrap.go:75] GET /api/v1/namespaces/kube-system/endpoints/kube-scheduler: (1.123312ms) 404 [[kube-scheduler/v1.6.0 (linux/amd64) kubernetes/fff5156/leader-election] 192.168.205.11:41912]
[vagrant@master01 ~]$ `

**Comment by ompraash** [comment]
@alexbrand i have set the memory as suggested.

```
boxes = [
    {
        :name => "etcd01",
        :eth1 => "192.168.205.10",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "master01",
        :eth1 => "192.168.205.11",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "worker01",
        :eth1 => "192.168.205.12",
        :mem => "2048",
        :cpu => "1"
    }
]
```

**Comment by ompraash** [comment]
i was able to resolve the issue. 
Solution: I had a vagrant image which was yet linked in the virtualbox causing the api-server to crashloop. Removing the image an rerunning helped me.
