### ISSUE TITLE
Add support for Vagrant

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic-provision#9]
Add support for provisioning nodes via Vagrant. We would need to generate a Vagrantfile and the plan file. It seems like after generating the Vagrantfile, we could execute vagrant for the user.

**Comment by codymccain** [comment]
@alexbrand I've just started coding this and should have an initial PR ready for review in the coming days.

The current roadmap for this is:
- Generate appropriate Vagrantfile (user manually executes vagrant up after generation)
- Execute `vagrant up` automatically
- Provide option for destroying the vagrant box

I'm providing both a "minikube like" single host and also allowing the user to specify cluster topology if desired.

**Comment by alexbrand** [comment]
Closed via #17
